# Minimal makefile 

# You can set these variables from the command line, and also
# from the environment for the first two.
PYTHON        = python3
CFGFILE       = ./config.yml

.PHONY: help 

html: 
	$(PYTHON) build.py $(CFGFILE)
